name: Daily rebuild

on:
  workflow_dispatch:
  schedule:
    # every day at 10:00 UTC (06:00 EDT/05:00 EST, 03:00 PDT/02:00 PST)
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.GATSBY_BUILD_URL }}
          method: 'GET'
          customHeaders: '{"x-gatsby-cloud-data-source": "gatsby-source-powerschedules"}'
